# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistance', '0002_auto_20180529_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistanceAnser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('assistance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assistance.Assistance')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='doctor')),
            ],
        ),
    ]
