# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 10:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('situation', models.CharField(blank=True, max_length=250, null=True)),
                ('enfant', models.CharField(blank=True, max_length=250, null=True)),
                ('motif', models.CharField(blank=True, max_length=250, null=True)),
                ('ville', models.CharField(blank=True, max_length=250, null=True)),
                ('voyage', models.CharField(blank=True, max_length=250, null=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='patient')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.Consultation'),
        ),
    ]
