# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-29 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='motif',
            field=models.CharField(choices=[('Ecoulement uretal', 'Ecoulement uretal'), ('Ecoulement anaux', 'Ecoulement anaux'), ('Douleurs anaux ou a la defacation', 'Douleurs anaux ou a la defacation'), ('Pertes vaginales', 'Perte vaginales'), ('Demangeaison', 'Demangeaison'), ('Douleur a la miction', 'Douleur a la miction'), ('Douleur lors des rapports sexuels', 'Douleur lors des rapports sexuels'), ('Douleur au bas ventre', 'Douleur au bas ventre'), ('Plaie genitale', 'Plaie genitale'), ('Plaie anale', 'Plaie anale'), ('Douleur et/ou Tumefaction du scrotum', 'Douleur et/ou Tumefaction du scrotum')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='situation',
            field=models.CharField(choices=[('Marie', 'Marie'), ('Divorce', 'Divorce'), ('Celibataire', 'Celibataire')], default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='voyage',
            field=models.CharField(choices=[('OUI', 'OUI'), ('NON', 'NON')], default=1, max_length=250),
            preserve_default=False,
        ),
    ]
